name: Go Build Binary

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  unit-test:
      name: "Unit Testing"
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Setup Go
          uses: actions/setup-go@v2
          with:
            go-version: 1.17
        - name: Running Unit-Test-Main-Svc
          working-directory: ./main-svc
          run: go test ./... -cover
          
  deploy:
      name: Build and deploy Shiny app
      runs-on: ubuntu-latest
      needs: "unit-test"
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Build and push Docker to Heroku
          env:
            HEROKU_APP_NAME: stoics-quote
            DOCKERFILE_DIRECTORY: "./main-svc/"
            HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
            HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
            DOCKERFILE_NAME: "Dockerfile"
            DOCKER_OPTIONS: "--no-cache"
          run: |
            cd ${DOCKERFILE_DIRECTORY}
            echo ${HEROKU_API_KEY} | docker login \
              --username=${HEROKU_EMAIL} \
              registry.heroku.com \
              --password-stdin
            docker build \
              --file ${DOCKERFILE_NAME} \
              ${DOCKER_OPTIONS} \
              --tag registry.heroku.com/${HEROKU_APP_NAME}/web .
            heroku container:push web --app ${HEROKU_APP_NAME}
            heroku container:release web --app ${HEROKU_APP_NAME}
