name: Go Build Binary

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  unit-test:
      name: "Unit Testing"
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Setup Go
          uses: actions/setup-go@v2
          with:
            go-version: 1.17
        - name: Running Unit-Test
          run: go test ./... -cover

  build-push-docker:
    name: Build docker image then push to docker hub
    runs-on: ubuntu-latest
    needs: "unit-test"
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Image
        run: docker build -t zeinfahrozi/main-svc:latest ./main-svc
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push image to Docker Hub
        run: docker push mugeki/laundro-api:1.0.0
